### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by muyuu** [muyuu/worcar#61]
### todos
- [x] `cmd` + `enter` as `new post` when new post page
- [ ] `j`, `k` as up or down postlist
- [ ] `shift` + `/` (means `?`) as focus search box

### use library to implement
- [react-shortcuts](https://www.npmjs.com/package/react-shortcuts)
